- type: department
  id: Frontier
  name: department-Frontier
  description: department-NF-description
  color: "#334E6D"
  weight: 50 # accounted for in jobs
  roles:
  - StationRepresentative
  #- DirectorOfCare # Null Sector
  - StationTrafficController
  - Valet # nyano
  - NFJanitor
  - MailCarrier # nyano
  #- SecurityGuard # Null Sector
  - Prisoner #nyano
  - Contractor # Frontier
  - Pilot # Frontier
  - Borg # Frontier
  
- type: department
  id: Antag
  name: department-Antag
  description: department-NFAntag-description
  color: "#DE3A3A"
  weight: -20 # accounted for in jobs
  roles:
  - PirateCaptain
  - PirateFirstMate
  - Pirate
  #- Prisoner #nyano
